service: sample-project

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-south-1
  
functions:
  app:
    handler: index.handler
    timeout: 300
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline
